---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecobee-exporter
  labels:
    app: ecobee-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecobee-exporter
  template:
    metadata:
      labels:
        app: ecobee-exporter
      annotations:
        oauth2-refresh-controller.cern.ch/to-inject: |
          [
            {
              "secretName": "ecobee-auth-token",
              "container": "ecobee-exporter",
              "owner": 0
            }
          ]      

    spec:
      containers:
      - image: petewall/ecobee-exporter
        name: ecobee-exporter
        env:
          - name: HANDLEAUTHREFRESH
            value: "false"
          - name: DEBUG
            value: "true"
          - name: AUTH_TOKEN_FILE
            value: "/tmp/oauthtk_0"
